server:
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        username: postgres
        password: admin
        url: jdbc:postgresql://localhost:5432/discord_clone
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    
security:
    jwt:
        secret: ======================Discord=Clone===========================
        expiration: 86400000
        cookieName: Discord_Clone_JWT